version: '3'

services:

  reverse-proxy:
    build:
      context: ./proxy
    network_mode: "host"
    environment:
      - TZ=America/Sao_Paulo
      
  application1:
    build:
      context: ./service1
    network_mode: "host"
    environment:
      - TZ=America/Sao_Paulo

  application2:
    build:
      context: ./service2
    network_mode: "host"
    environment:
      - TZ=America/Sao_Paulo